import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeInitializerWrapper from "./components/ThemeInitializerWrapper";
import DrawerMenuWrapper from "./components/DrawerMenuWrapper";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ThemeInitializerWrapper />
        {children}
      </body>
    </html>
  );
}
